sudo: false
language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "16"
cache:
  directories:
    - node_modules
script: "npm run testonly:cov"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
